// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgUpdateAuthorizedAddress } from "./types/fairyring/conditionalenc/tx";
import { MsgCreateAuthorizedAddress } from "./types/fairyring/conditionalenc/tx";
import { MsgSendConditionalenc } from "./types/fairyring/conditionalenc/tx";
import { MsgRegisterValidator } from "./types/fairyring/conditionalenc/tx";
import { MsgCreateLatestPubKey } from "./types/fairyring/conditionalenc/tx";
import { MsgDeleteAuthorizedAddress } from "./types/fairyring/conditionalenc/tx";

import { AggregatedKeyShare as typeAggregatedKeyShare} from "./types"
import { AggregatedConditionalKeyShare as typeAggregatedConditionalKeyShare} from "./types"
import { AuthorizedAddress as typeAuthorizedAddress} from "./types"
import { KeyShare as typeKeyShare} from "./types"
import { ConditionalKeyShare as typeConditionalKeyShare} from "./types"
import { Params as typeParams} from "./types"
import { ActivePubKey as typeActivePubKey} from "./types"
import { QueuedPubKey as typeQueuedPubKey} from "./types"
import { ValidatorSet as typeValidatorSet} from "./types"

export { MsgUpdateAuthorizedAddress, MsgCreateAuthorizedAddress, MsgSendConditionalenc, MsgRegisterValidator, MsgCreateLatestPubKey, MsgDeleteAuthorizedAddress };

type sendMsgUpdateAuthorizedAddressParams = {
  value: MsgUpdateAuthorizedAddress,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateAuthorizedAddressParams = {
  value: MsgCreateAuthorizedAddress,
  fee?: StdFee,
  memo?: string
};

type sendMsgSendConditionalencParams = {
  value: MsgSendConditionalenc,
  fee?: StdFee,
  memo?: string
};

type sendMsgRegisterValidatorParams = {
  value: MsgRegisterValidator,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateLatestPubKeyParams = {
  value: MsgCreateLatestPubKey,
  fee?: StdFee,
  memo?: string
};

type sendMsgDeleteAuthorizedAddressParams = {
  value: MsgDeleteAuthorizedAddress,
  fee?: StdFee,
  memo?: string
};


type msgUpdateAuthorizedAddressParams = {
  value: MsgUpdateAuthorizedAddress,
};

type msgCreateAuthorizedAddressParams = {
  value: MsgCreateAuthorizedAddress,
};

type msgSendConditionalencParams = {
  value: MsgSendConditionalenc,
};

type msgRegisterValidatorParams = {
  value: MsgRegisterValidator,
};

type msgCreateLatestPubKeyParams = {
  value: MsgCreateLatestPubKey,
};

type msgDeleteAuthorizedAddressParams = {
  value: MsgDeleteAuthorizedAddress,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

interface MsgSubmitEncryptedTx {
	 creator :string
	 data:string
	 condition: number;
}

interface SubmitEncryptedTxParams {
	value: MsgSubmitEncryptedTx;
	fee?: StdFee;
	memo?: string
}

interface MsgSubmitEncryptedTxResponse {}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		async SubmitEncryptedTx({ value, fee, memo }: SubmitEncryptedTxParams): Promise<MsgSubmitEncryptedTxResponse> {
			if (!signer) {
					throw new Error('TxClient:SubmitEncryptedTx: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSendConditionalenc({ value: MsgSendConditionalenc.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:SubmitEncryptedTx: Could not broadcast Tx: '+ e.message)
			}
		},

		async sendMsgUpdateAuthorizedAddress({ value, fee, memo }: sendMsgUpdateAuthorizedAddressParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgUpdateAuthorizedAddress: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgUpdateAuthorizedAddress({ value: MsgUpdateAuthorizedAddress.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgUpdateAuthorizedAddress: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateAuthorizedAddress({ value, fee, memo }: sendMsgCreateAuthorizedAddressParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateAuthorizedAddress: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateAuthorizedAddress({ value: MsgCreateAuthorizedAddress.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateAuthorizedAddress: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSendConditionalenc({ value, fee, memo }: sendMsgSendConditionalencParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSendConditionalenc: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSendConditionalenc({ value: MsgSendConditionalenc.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSendConditionalenc: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRegisterValidator({ value, fee, memo }: sendMsgRegisterValidatorParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRegisterValidator: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRegisterValidator({ value: MsgRegisterValidator.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRegisterValidator: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreateLatestPubKey({ value, fee, memo }: sendMsgCreateLatestPubKeyParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreateLatestPubKey: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreateLatestPubKey({ value: MsgCreateLatestPubKey.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreateLatestPubKey: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDeleteAuthorizedAddress({ value, fee, memo }: sendMsgDeleteAuthorizedAddressParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDeleteAuthorizedAddress: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDeleteAuthorizedAddress({ value: MsgDeleteAuthorizedAddress.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDeleteAuthorizedAddress: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgUpdateAuthorizedAddress({ value }: msgUpdateAuthorizedAddressParams): EncodeObject {
			try {
				return { typeUrl: "/fairyring.conditionalenc.MsgUpdateAuthorizedAddress", value: MsgUpdateAuthorizedAddress.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgUpdateAuthorizedAddress: Could not create message: ' + e.message)
			}
		},
		
		msgCreateAuthorizedAddress({ value }: msgCreateAuthorizedAddressParams): EncodeObject {
			try {
				return { typeUrl: "/fairyring.conditionalenc.MsgCreateAuthorizedAddress", value: MsgCreateAuthorizedAddress.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateAuthorizedAddress: Could not create message: ' + e.message)
			}
		},
		
		msgSendConditionalenc({ value }: msgSendConditionalencParams): EncodeObject {
			try {
				return { typeUrl: "/fairyring.conditionalenc.MsgSendConditionalenc", value: MsgSendConditionalenc.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSendConditionalenc: Could not create message: ' + e.message)
			}
		},
		
		msgRegisterValidator({ value }: msgRegisterValidatorParams): EncodeObject {
			try {
				return { typeUrl: "/fairyring.conditionalenc.MsgRegisterValidator", value: MsgRegisterValidator.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRegisterValidator: Could not create message: ' + e.message)
			}
		},
		
		msgCreateLatestPubKey({ value }: msgCreateLatestPubKeyParams): EncodeObject {
			try {
				return { typeUrl: "/fairyring.conditionalenc.MsgCreateLatestPubKey", value: MsgCreateLatestPubKey.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreateLatestPubKey: Could not create message: ' + e.message)
			}
		},
		
		msgDeleteAuthorizedAddress({ value }: msgDeleteAuthorizedAddressParams): EncodeObject {
			try {
				return { typeUrl: "/fairyring.conditionalenc.MsgDeleteAuthorizedAddress", value: MsgDeleteAuthorizedAddress.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDeleteAuthorizedAddress: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						AggregatedKeyShare: getStructure(typeAggregatedKeyShare.fromPartial({})),
						AggregatedConditionalKeyShare: getStructure(typeAggregatedConditionalKeyShare.fromPartial({})),
						AuthorizedAddress: getStructure(typeAuthorizedAddress.fromPartial({})),
						KeyShare: getStructure(typeKeyShare.fromPartial({})),
						ConditionalKeyShare: getStructure(typeConditionalKeyShare.fromPartial({})),
						Params: getStructure(typeParams.fromPartial({})),
						ActivePubKey: getStructure(typeActivePubKey.fromPartial({})),
						QueuedPubKey: getStructure(typeQueuedPubKey.fromPartial({})),
						ValidatorSet: getStructure(typeValidatorSet.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			FairyringConditionalenc: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;